# Generated by Django 3.0.8 on 2020-07-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='total',
            new_name='quantity',
        ),
    ]
