# Generated by Django 3.0.8 on 2020-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200705_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spent_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
